version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8267
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500M
volumes:
  db:
    driver: local