spring:
  app:
    name: PizzaApp
    version: 1.0.0
    description: PizzaApp
  main:
    allow-circular-references: true
  jpa:
    database: POSTGRESQL
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    sql:
      init:
        platform: postgres
camunda:
  bpm:
    default-serialization-format: application/json
    admin-user:
      id: admin
      password: admin
    job-execution:
      enabled: true
      max-jobs-per-acquisition: 5
      max-pool-size: 20
    id-generator: simple
    generic-properties:
      properties:
        historyCleanupBatchWindowStartTime: "01:00"
        historyCleanupBatchWindowEndTime: "09:00"
        historyCleanupStrategy: endTimeBased
---
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 8267
    driverClassName: org.postgresql.Driver